import convict from 'convict';

const config = convict({
  calendar: {
    googleServiceEmail: {
      doc: 'The google email address generated by developer console',
      default: null,
      format: String,
      env: 'GOOGLE_SERVICE_EMAIL'
    },
    googleServiceKeypath: {
      doc: 'Absolute path to service account .PEM file',
      default: null,
      format: String,
      env: 'GOOGLE_SERVICE_KEYPATH'
    },
    googleSubjectEmail: {
      doc: 'An email to be impersonated to get access to resource calendars',
      default: '',
      format: String,
      env: 'GOOGLE_SUBJECT_EMAIL'
    }
  }
});

export default config;
